name: alpha
description: "The companion app for the IIC Cashflow Game"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  lottie: ^3.1.2
  get_it: ^7.7.0
  vector_math: ^2.1.4
  logging: ^1.2.0
  intl: ^0.19.0
  confetti: ^0.8.0
  carousel_slider: ^5.0.0
  auto_size_text: ^3.0.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/anim/
    - assets/images/
    - assets/images/avatars/
    - assets/images/logo/
    - assets/images/dashboard/
    - assets/images/budgeting/
    - assets/images/career/
    - assets/images/real_estate/
    - assets/images/car/
    - assets/images/personal_life/

  fonts:
    - family: PublicSans
      fonts:
        - asset: assets/fonts/PublicSans/PublicSans-Black.ttf
          weight: 900

    - family: LexendMega
      fonts:
        - asset: assets/fonts/LexendMega/LexendMega-Black.ttf
          weight: 900
        - asset: assets/fonts/LexendMega/LexendMega-ExtraBold.ttf
          weight: 900

    - family: MazzardH
      fonts:
        - asset: assets/fonts/MazzardH/MazzardH-Bold.ttf
          weight: 700
        - asset: assets/fonts/MazzardH/MazzardH-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/MazzardH/MazzardH-Medium.ttf
          weight: 500

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
