import 'package:flutter/material.dart';

class AlphaTextStyles {
  static const textBold10 =
      TextStyle(fontWeight: FontWeight.w700, fontSize: 10.0);
  static const textBold11 =
      TextStyle(fontWeight: FontWeight.w700, fontSize: 11.0);
  static const textBold12 =
      TextStyle(fontWeight: FontWeight.w700, fontSize: 12.0);
  static const textBold13 =
      TextStyle(fontWeight: FontWeight.w700, fontSize: 13.0);
  static const textBold14 =
      TextStyle(fontWeight: FontWeight.w700, fontSize: 14.0);
  static const textBold15 =
      TextStyle(fontWeight: FontWeight.w700, fontSize: 15.0);
  static const textBold16 =
      TextStyle(fontWeight: FontWeight.w700, fontSize: 16.0);
  static const textBold17 =
      TextStyle(fontWeight: FontWeight.w700, fontSize: 17.0);
  static const textBold18 =
      TextStyle(fontWeight: FontWeight.w700, fontSize: 18.0);
  static const textBold19 =
      TextStyle(fontWeight: FontWeight.w700, fontSize: 19.0);
  static const textBold20 =
      TextStyle(fontWeight: FontWeight.w700, fontSize: 20.0);
  static const textBold21 =
      TextStyle(fontWeight: FontWeight.w700, fontSize: 21.0);
  static const textBold22 =
      TextStyle(fontWeight: FontWeight.w700, fontSize: 22.0);
  static const textBold23 =
      TextStyle(fontWeight: FontWeight.w700, fontSize: 23.0);
  static const textBold24 =
      TextStyle(fontWeight: FontWeight.w700, fontSize: 24.0);
  static const textBold25 =
      TextStyle(fontWeight: FontWeight.w700, fontSize: 25.0);
  static const textBold26 =
      TextStyle(fontWeight: FontWeight.w700, fontSize: 26.0);
  static const textBold27 =
      TextStyle(fontWeight: FontWeight.w700, fontSize: 27.0);
  static const textBold28 =
      TextStyle(fontWeight: FontWeight.w700, fontSize: 28.0);
  static const textBold29 =
      TextStyle(fontWeight: FontWeight.w700, fontSize: 29.0);
  static const textBold30 =
      TextStyle(fontWeight: FontWeight.w700, fontSize: 30.0);
  static const textBold31 =
      TextStyle(fontWeight: FontWeight.w700, fontSize: 31.0);
  static const textBold32 =
      TextStyle(fontWeight: FontWeight.w700, fontSize: 32.0);
  static const textBold33 =
      TextStyle(fontWeight: FontWeight.w700, fontSize: 33.0);
  static const textBold34 =
      TextStyle(fontWeight: FontWeight.w700, fontSize: 34.0);
  static const textBold35 =
      TextStyle(fontWeight: FontWeight.w700, fontSize: 35.0);
  static const textBold36 =
      TextStyle(fontWeight: FontWeight.w700, fontSize: 36.0);
  static const textBold37 =
      TextStyle(fontWeight: FontWeight.w700, fontSize: 37.0);
  static const textBold38 =
      TextStyle(fontWeight: FontWeight.w700, fontSize: 38.0);
  static const textBold39 =
      TextStyle(fontWeight: FontWeight.w700, fontSize: 39.0);
  static const textBold40 =
      TextStyle(fontWeight: FontWeight.w700, fontSize: 40.0);

  static const textBlack10 =
      TextStyle(fontWeight: FontWeight.w900, fontSize: 10.0);
  static const textBlack11 =
      TextStyle(fontWeight: FontWeight.w900, fontSize: 11.0);
  static const textBlack12 =
      TextStyle(fontWeight: FontWeight.w900, fontSize: 12.0);
  static const textBlack13 =
      TextStyle(fontWeight: FontWeight.w900, fontSize: 13.0);
  static const textBlack14 =
      TextStyle(fontWeight: FontWeight.w900, fontSize: 14.0);
  static const textBlack15 =
      TextStyle(fontWeight: FontWeight.w900, fontSize: 15.0);
  static const textBlack16 =
      TextStyle(fontWeight: FontWeight.w900, fontSize: 16.0);
  static const textBlack17 =
      TextStyle(fontWeight: FontWeight.w900, fontSize: 17.0);
  static const textBlack18 =
      TextStyle(fontWeight: FontWeight.w900, fontSize: 18.0);
  static const textBlack19 =
      TextStyle(fontWeight: FontWeight.w900, fontSize: 19.0);
  static const textBlack20 =
      TextStyle(fontWeight: FontWeight.w900, fontSize: 20.0);
  static const textBlack21 =
      TextStyle(fontWeight: FontWeight.w900, fontSize: 21.0);
  static const textBlack22 =
      TextStyle(fontWeight: FontWeight.w900, fontSize: 22.0);
  static const textBlack23 =
      TextStyle(fontWeight: FontWeight.w900, fontSize: 23.0);
  static const textBlack24 =
      TextStyle(fontWeight: FontWeight.w900, fontSize: 24.0);
  static const textBlack25 =
      TextStyle(fontWeight: FontWeight.w900, fontSize: 25.0);
  static const textBlack26 =
      TextStyle(fontWeight: FontWeight.w900, fontSize: 26.0);
  static const textBlack27 =
      TextStyle(fontWeight: FontWeight.w900, fontSize: 27.0);
  static const textBlack28 =
      TextStyle(fontWeight: FontWeight.w900, fontSize: 28.0);
  static const textBlack29 =
      TextStyle(fontWeight: FontWeight.w900, fontSize: 29.0);
  static const textBlack30 =
      TextStyle(fontWeight: FontWeight.w900, fontSize: 30.0);
  static const textBlack31 =
      TextStyle(fontWeight: FontWeight.w900, fontSize: 31.0);
  static const textBlack32 =
      TextStyle(fontWeight: FontWeight.w900, fontSize: 32.0);
  static const textBlack33 =
      TextStyle(fontWeight: FontWeight.w900, fontSize: 33.0);
  static const textBlack34 =
      TextStyle(fontWeight: FontWeight.w900, fontSize: 34.0);
  static const textBlack35 =
      TextStyle(fontWeight: FontWeight.w900, fontSize: 35.0);
  static const textBlack36 =
      TextStyle(fontWeight: FontWeight.w900, fontSize: 36.0);
  static const textBlack37 =
      TextStyle(fontWeight: FontWeight.w900, fontSize: 37.0);
  static const textBlack38 =
      TextStyle(fontWeight: FontWeight.w900, fontSize: 38.0);
  static const textBlack39 =
      TextStyle(fontWeight: FontWeight.w900, fontSize: 39.0);
  static const textBlack40 =
      TextStyle(fontWeight: FontWeight.w900, fontSize: 40.0);
}
